### ISSUE TITLE
gopro 4 Code Pairing

### ISSUE THREAD

**Issue by dengyunjie** [KonradIT/goprowifihack#104]
**Problem:**

We have been connected to the gopro-bp - (digital) password: "goprohero，then call this URL :
https://10.5.5.9/gpPair?c=start&pin=XXXX&mode=0,XXXX is the 4 digit PIN on the GoPro front screen.
But it returns “BT: RECV: HTTP/1.1 400 Bad Request， Connection: close” .The picture and camera instructions are normal

**Details:**

* GoPro Camera(s):  GoPro 4
* Firmware Version:
* Steps to reproduce:
* Happens every time? [Y/N]:  Y

**Comment by KonradIT** [comment]
You need to use SSL in the request. see gopro-py-api
