### ISSUE TITLE
Pairing HERO(2018) without PIN to PC-Wifi (solved)

### ISSUE THREAD

**Issue by distancerunner** [KonradIT/goprowifihack#121]
**Problem:**

The Hero4 Commands describe a pairing with PIN entering. But in the Hero(2018) no Pin is needed. So no command is given in the DOC

**Details:**
I used PacketCapture for Android and scanned the WIFI Traffic from the GoPro App.
For Adding the Computer to the Device List in the GoPro(2018) the make folowing procedure:
GET: http://10.5.5.9/bacpac/cv

GET: http://10.5.5.9/gp/gpControl/command/wireless/pair/complete?success=1&deviceName=WIN10

as deviceName you can choose your own device name.

I tried it with the computer and it worked perfectly. Please add it to the docs.

nice regards
Gregor Schulze

**Comment by KonradIT** [comment]
https://github.com/KonradIT/goprowifihack/commit/2511520748a4818d049a1e37a4510f030b8bc43e
