### ISSUE TITLE
Hero4 Silver Cannot stream with ffplay

### ISSUE THREAD

**Issue by tony056** [KonradIT/goprowifihack#13]
My gopro responsed me 
`{"status":"0"}`
I used the url: `http://10.5.5.9/gp/gpExec?p1=gpStreamA9&c1=restart`

However, when I tried to use ffplay -an udp://:8554 to stream from gopro
the result is as below:
`Could not find codec parameters for stream 0 (Audio: aac (LC), 5.0, fltp, 206 kb/s): unspecified sample rate
Consider increasing the value for the 'analyzeduration' and 'probesize' options
udp://:8554: could not find codec parameters`

Can someone help me with this problem?
Thank you!

**Comment by KonradIT** [comment]
Try  
    
    ffplay udp://@:8554
