### ISSUE TITLE
What is the command to delete a single file?

### ISSUE THREAD

**Issue by bcasinclair** [KonradIT/goprowifihack#14]
I see you have camera/df but what parameter needs to go in to that?

I have tried a few with no luck

**Comment by KonradIT** [comment]
Check the HERO4.md file, its in there :)

**Comment by truefishcoder** [comment]
http://10.5.5.9/gp/gpControl/command/storage/delete/last
works for last file on Hero4
http://10.5.5.9/gp/gpControl/command/storage/delete/all  deletes all files

**Comment by KonradIT** [comment]
The URL for deleting a file is in https://github.com/KonradIT/goprowifihack/blob/master/HERO4/WifiCommands.md#delete-file
