### ISSUE TITLE
Media Thumbnail not working , way?

### ISSUE THREAD

**Issue by mikinet1** [KonradIT/goprowifihack#143]
How To get the thumbnail of a photo using : http://10.5.5.9/gp/gpMediaMetadata?p=XXXGOPRO/GOPRXXXX.JPG

i get empty array .
also in the browser.

it's not seems to be self-explanatory.
is it working or not? 
need help.

**Comment by KonradIT** [comment]
You need to replace XXXGOPRO with the right folder and GOPRXXXX.JPG with the right filename.

**Comment by mikinet1** [comment]
i did it, and it's dose not work.
