### ISSUE TITLE
Hero5black - change wifi frequency of camera's AccessPoint (App-Mode/ Client (RC-Mode) 

### ISSUE THREAD

**Issue by habakuk39** [KonradIT/goprowifihack#150]
@konradIT:

Is it possible to set the wifi freqency of the hero5black permanently on either 2.4 or5 MHz band?
Is it even possible to make the camera doing the AP on one frequency  (2,4MHz) while the client was listening on the other frequency (5 Mhz)? 

I have to catch the gopro_s wificlient with an 5 Mhz Accesspoint due to several reasons.

Any ideas?

* GoPro Camera(s): Hero5black
* Firmware Version: 2.60

**Comment by KonradIT** [comment]
no.

**Comment by habakuk39** [comment]
When/what for does it use the 5Mhz in AP mode?
