### ISSUE TITLE
GoPro5black: changing the APs SSID and PWD - youtube video

### ISSUE THREAD

**Issue by habakuk39** [KonradIT/goprowifihack#151]
@konradIT:

You've made this youtube video:
https://www.youtube.com/watch?v=5FHdcvFiLR4

you are describing an important fix but unfortunately the videos quality is so bad that I do not get the file's name you are nano-ing nor the code you are writing in.

Can you briefly explain again please how you are doing it?

**Comment by KonradIT** [comment]
https://github.com/KonradIT/GoProWirelessPassword/blob/master/code/GoPro_Password_Change.sh
