### ISSUE TITLE
Secondary modes not working 

### ISSUE THREAD

**Issue by digaus** [KonradIT/goprowifihack#16]
Somehow the secondary modes for the GoPro Hero 4 are not working... Also the Protune Settings are only working for the video mode and not for Photo or MultiShot :/ tried to find the settings but no succes

**Comment by KonradIT** [comment]
what firmware?

**Comment by digaus** [comment]
HD4.02.03.00.00

**Comment by ztzhang** [comment]
It seems that the urls are incomplete for current firmware. I sniffed the GP Hero4 urls with the latest firmware, please refer to the latest issue.

**Comment by depodefi** [comment]
Is there any progress on solving that issue?

**Comment by ztzhang** [comment]
You can try this out: https://github.com/ztzhang/GoProWifiCommand

**Comment by depodefi** [comment]
It's working, although you got some typos _submode_ instead of _sub_mode_

**Comment by ztzhang** [comment]
It seems to be a firmware issue. Some firmware uses sub_mode instead.

**Comment by KonradIT** [comment]
I updated the repo with the latest URLs from the latest FW (HERO4 Black 3.00 July 30, 2015)
