### ISSUE TITLE
Hero 8 / Hero Max packet sniffing

### ISSUE THREAD

**Issue by demiantres** [KonradIT/goprowifihack#166]
Has anyone successfully intercepted the communication between the GoPro Hero 8 or Max camera and the Android GoPro app? Everytime when I turn on the Android packet sniffer app then the GoPro app rejects to connect.

**Comment by KonradIT** [comment]
Yeah I use Packet Sniffer from the Play store which works.

**Comment by demiantres** [comment]
On a rooted device? I have this problem only with the new Hero cameras. The Hero 7 and older work fine.

**Comment by demiantres** [comment]
Got it working on an older device.
