### ISSUE TITLE
TRIM

### ISSUE THREAD

**Issue by raffacolosimo** [KonradIT/goprowifihack#17]
A few monts ago Gopro introduced a new TRIM functionality in his app.
By this new function you can get a selected part of a video via wifi without downloading the entire file.
Any information is missing about it, but I'm pretty sure it's a feature involving an indocumented wifi command.
Do you know anything about it?
May I help you in discovering this?
Thanks a lot for your work
Raffaello

**Comment by KonradIT** [comment]
@raffacolosimo https://github.com/KonradIT/goprowifihack/blob/master/HERO4/WifiCommands.md#extracting-a-clip-from-a-video-gopro-clips
