### ISSUE TITLE
Unable to achieve live stream

### ISSUE THREAD

**Issue by rufrajput** [KonradIT/goprowifihack#172]
**Problem:**

I am unable to get live stream in my android application

**Details:**

I executed other commands on my Go Pro Hero 7 Black, successfully, but I am stuck on achieving live preview of camera in my app. I also tried udp stream url, but nothing happend
Kindly tell me how to achieve this.
screen shot of live preview in official app of go pro is attached
![device-2020-01-06-174446](https://user-images.githubusercontent.com/45385527/71819446-c4f3aa00-30ad-11ea-9eae-45265c161832.png)

**Comment by KonradIT** [comment]
I've had minimal success using FFmpeg bindings for Java, transcoding to udp on localhost, and playing back on LibVLC for Android.
