### ISSUE TITLE
FPS is resolution dependant

### ISSUE THREAD

**Issue by alexismo** [KonradIT/goprowifihack#18]
The resolution commands don't always respond correctly and are not always mapped correctly either.

For example, in 4K Superview, the only framerate usable is 24. The GoPro will respond 200 on all commands to change the framerate, but it **will not change**.

See http://shop.gopro.com/APAC/cameras/hero4-black/CHDHX-401-EU.html for resolution * framerate equivalencies. The framerate called depends on the "stack" of accepted framerates for that resolution.

For example, setting the video resolution to 1440 will have /setting/2/0 respond as 80 fps, but setting the video resolution to 960p will have /setting/2/0 respond as 120 fps.

**Comment by KonradIT** [comment]
I will do a table to show this, feel free to add details yourself!
