### ISSUE TITLE
could not get data from unsecured endpoint

### ISSUE THREAD

**Issue by Akhouad** [KonradIT/goprowifihack#181]
**Problem:**
I am trying to get goPro data from an app built with ionic, I am sending requests with axios, but it seems that i couldn't get data from this endpoint because it is not SSL secured:
http://10.5.5.9/gp/gpControl/status

the URL works if I access it from the mobile browser but it doesn't work in the app

**Details:**

* GoPro Camera(s): Hero 7

**Comment by KonradIT** [comment]
That's... Out of the scope of this repository.
