### ISSUE TITLE
TimeLapse Interval

### ISSUE THREAD

**Issue by Joseph310** [KonradIT/goprowifihack#2]
Hello,

I was not able to set the time lapse interval with you url code. 

I tried: http://10.5.5.9/camera/TI?t=MYPASSWORD&p=%1e

Has this maybe changed?

Thanks

**Comment by hellolee1234** [comment]
It seems that the server of http://10.5.5.9/ is DOWN!

All the link to the server is un-accessible.

Example:
http://10.5.5.9/camera/TI?t=MYPASSWORD&p=%1e

**Comment by KonradIT** [comment]
The GoPro's WiFi needs ti be paired with whatever device you are triggering the URL with. Test o  HERO3 Black: pending
