### ISSUE TITLE
Urls for Gopro Hero4 is incomplete

### ISSUE THREAD

**Issue by ztzhang** [KonradIT/goprowifihack#20]
I tested the urls given, and it seems to be incomplete.
I sniffed the gopro app and completed the urls here: https://github.com/ztzhang/GoProWifiCommand
Would it be possible for you to update your files?
Thanks.

**Comment by KonradIT** [comment]
Yes, will update in a couple hours

**Comment by KonradIT** [comment]
Too many things going on, I plan to do a complete rewrite of this repo with all the WiFi commands/media server/camera info URL this weekend (each command will be tested on my cameras to verify that it works)
