### ISSUE TITLE
720p live streaming support (like Periscope)

### ISSUE THREAD

**Issue by Duffycola** [KonradIT/goprowifihack#21]
Do you have any idea how Periscope managed to achieve 720p live streaming? Here are some interesting comments: http://edbrophy.com/periscope-gopro-clearing-up-the-misinformation/

**Comment by KonradIT** [comment]
I will have access to an iOS device next week so I will investigate it

**Comment by KonradIT** [comment]
Looks like if you do a UDP wakeup call it starts the stream at 720p 

Tested: no

**Comment by dvize** [comment]
Is there any more information on this?

**Comment by sfarges** [comment]
The gopro hero4 stream received by Periscope is 432 x 240. This is not 720p.
Resizing it to 720 during re-encoding on phone or on servers dont improve the low quality.

**Comment by KonradIT** [comment]
@sfarges oh well, that is quite embarrasing then

**Comment by KonradIT** [comment]
Should I close the issue?

**Comment by dvize** [comment]
Makes sense to close since it is not feasible.  Now i know i have to get a capture card.
