### ISSUE TITLE
Number of photos or video duration

### ISSUE THREAD

**Issue by tinytracker** [KonradIT/goprowifihack#22]
Not quite an issue, but would anyone happen to know if its possible to GET the number of photos taken (shown on the display) or video duration?

**Comment by KonradIT** [comment]
That will be documented in the next update of the API, but only for HERO4 cameras

**Comment by KonradIT** [comment]
https://github.com/KonradIT/goprowifihack/blob/master/HERO4/CameraStatus.md#status-object

38 for number of pictures and 13 for current video duration
