### ISSUE TITLE
Link UN-accessible

### ISSUE THREAD

**Issue by hellolee1234** [KonradIT/goprowifihack#23]
Dear Sir,

Your Server is DOWN!

http://10.5.5.9/gp/gpControl/setting/26/8

**Comment by xotmatrix** [comment]
That is the IP address of whatever camera you have connected to via Wi-Fi. It is a local web server running on the camera, not an internet web server.

**Comment by KonradIT** [comment]
As @xotmatrix said, you need to be connected to the GoPro's WiFi
