### ISSUE TITLE
Hero5black - BLE command to initiate pairing of gopro

### ISSUE THREAD

**Issue by habakuk1979** [KonradIT/goprowifihack#245]
@KonradIT 
@cepoon 

Hi there!

I am not absolutely sure but I think that some months ago I accidentialy stumbled over a **BLE-command to bring Hero5black to pairing mode** for new device: 

1.) connections -->new device -->GoProApp 
and /or
2.) connections --> newdevice --> Smart Remote

**Comment by KonradIT** [comment]
Hi, yes, this is how you pair the camera for the first time.

**Comment by habakuk1979** [comment]
@KonradIT 
yes I know.

but I am searching the BLE command to bring the camera (again) in this mode, unattended.
Which command?

sudo gatttool -t random -b xx:xx:xx:xx:xx:xx --char-write-req -a 0xxx -n xxxxxxx

**Comment by KonradIT** [comment]
Hi, no idea.
