### ISSUE TITLE
Wonders sometimes happen - official documentation from GoPro for Wifi and BLE !

### ISSUE THREAD

**Issue by rhoenschrat** [KonradIT/goprowifihack#249]
Just got the following link 
https://gopro.github.io/OpenGoPro/

**Comment by KonradIT** [comment]
Yep!! I've been in contact with them regarding this new API, and just made public my changes on [gopro-ble-py](http://github.com/konradit/gopro-ble-py) and [gopro-py-api](http://github.com/konradit/gopro-py-api)

**Comment by KonradIT** [comment]
https://github.com/konradit/goprowifihack#this-vs-opengopro
