### ISSUE TITLE
How to capture commands

### ISSUE THREAD

**Issue by TheGreyDiamond** [KonradIT/goprowifihack#252]
**Problem:**

I want/need to capture new commands from the GoPro QUIK app. I wanted to use Packet Capture, however, the moment I enable any kind of a VPN (like Packet Capture or Netguard) GoPro QUIK losses connection to the camera. Any idea why this happens?

* GoPro Camera(s): GoPro Hero 7 black

**Comment by KonradIT** [comment]
Start the VPN after you connect to the camera on the app.

**Comment by TheGreyDiamond** [comment]
Last time I tried it also failed. I had the GoPro app and Packet capture open next to each other on my tablet and the moment I start the packet capture the GoPro app shows a dialogue saying it has lost connection to my GoPro. Even tho I was seeing the live preview (until I started the packet capture). So I was connected.

**Comment by TheGreyDiamond** [comment]
So, any idea?
