### ISSUE TITLE
Turbo Transfer

### ISSUE THREAD

**Issue by jacobstasiewicz** [KonradIT/goprowifihack#255]
**Problem:**
I have been looking at https://gopro.github.io/OpenGoPro/ble for getting requests and I notice they have a turbo transfer option, I got it to work on my raspberry pi, the camera will say it is transferring photos but I can not seem to find where they are going or how to control which directory they will end up in. Has anyone experimented with this?

**Details:**

* GoPro Camera(s):  Hero 9
* Firmware Version:  1.00
* Steps to reproduce:  N/A
* Happens every time? [Y/N]: Y

**Comment by KonradIT** [comment]
That's not how it works.

The mode simply makes any GET request return data faster.
