### ISSUE TITLE
Command for putting GoPro MAX into "360 Video" mode

### ISSUE THREAD

**Issue by MDThomsen** [KonradIT/goprowifihack#270]
Under the MAX documentation I can't seem to find a command for changing the filming mode to 360 Video. Is this even possible to do over WiFI, or can it only be done through BLE?

**Comment by KonradIT** [comment]
It would be:

http://10.5.5.9/gp/gpControl/setting/142/$lensmode

$lensmode:

0 = HeroMode
1 = 360
