### ISSUE TITLE
Can't get mediafile metadata on GOPRO MAX

### ISSUE THREAD

**Issue by EvgenyKhlivetsky** [KonradIT/goprowifihack#297]
**Problem:**

Hey @KonradIT thanks for the repo!
I want to get media file metadata with the help of https://github.com/KonradIT/goprowifihack/blob/master/MAX/Mediabrowsing.md.
First I get the media list with: http://10.5.5.9:8080/gp/gpMediaList. I receive something like this (filename and directory name are correct):

```
{
  id: "123...455",
  media: [
    {
      d: "100GOPRO",
      fs: [
        {
          n: "GH010137.MP4",
          cre: 1726566942,
          mod: 1726566942,
          s: 20609033,
        }, //... more files
      ],
    },
  ],
};
```
Then I want to get particular file metadata with http://10.5.5.9/gp/gpMediaMetadata?p=/XXXGOPRO/GOPRXXXX.MP4&t=v4info, but here I already have a question. Why there is no port number in this URL? Second question is why sometimes "p"(path?) starts with forward slash, as with the URL above, and sometimes it is not, as for photos: http://10.5.5.9/gp/gpMediaMetadata?p=XXXGOPRO/GOPRXXXX.JPG&t=v4info. 

The URLs I tried:
http://10.5.5.9:8080/gp/gpMediaMetadata?p=/100GOPRO/GH010138.MP4&t=videoinfo
http://10.5.5.9:8080/gp/gpMediaMetadata?p=100GOPRO/GH010138.MP4&t=videoinfo (without slash)
http://10.5.5.9/gp/gpMediaMetadata?p=/100GOPRO/GH010138.MP4&t=videoinfo (without port)
http://10.5.5.9/gp/gpMediaMetadata?p=100GOPRO/GH010138.MP4&t=videoinfo (without port and slash)
http://10.5.5.9:8080/gp/gpMediaMetadata?p=/100GOPRO/GOPR010138.MP4&t=videoinfo (GOPR instead of GH, just trying to match the doc) and some more variants, but nothing helps :/ 

**Details:**
Why I need this is because "cre" from gpMediaList is incorrect, I live in UTC+3 and "cre" is 3 hours in the future for each recording. But when I insert an SD card into my laptop the metadata is correct and it shows creation date correctly. Maybe I don't understand something, but it looks like some bug in gopro max for me. Thanks in advance!

* GoPro Camera(s): GOPRO MAX
* Firmware Version: v02.02.00

**Comment by KonradIT** [comment]
Hi, what was the solution?

**Comment by EvgenyKhlivetsky** [comment]
It's just a typo @KonradIT, sorry for disturbing :D But I am still curious about this Q: "Why I need this is because "cre" from gpMediaList is incorrect, I live in UTC+3 and "cre" is 3 hours in the future for each recording. But when I insert an SD card into my laptop the metadata is correct and it shows creation date correctly. Maybe I don't understand something, but it looks like some bug in gopro max for me. Thanks in advance!"
Basically, what I mean. Let's say I start recording now- 1726575091, I get this value from the camera via BLE with get date time and then converting to the seconds since epoch. I tested it and it works correctly. Then I capture a video. Connect to the camera via wifi, make this request: http://10.5.5.9:8080/gp/gpMediaList, and I see that timestamp is 3 hours in the future- 1726585891. But when I insert SD card in my laptop- the date is correct. When I download the video via gopro quick and look metadata via iPhone "Photos" app, it also displays correct date, but it says "Adjusted" and if I revert it, then the time of recording will be also 3 hours in the future.

Sorry, if it is confusing, hope you got what I mean. Is this a bug related to gopro max not having a timezone setting? Thanks :)
