### ISSUE TITLE
Pairing URL is wrong

### ISSUE THREAD

**Issue by zaur** [KonradIT/goprowifihack#50]
####Problem:
The following URL for pairing the device is wrong.
http://10.5.5.9/gpPair?c=start&pin=XXXXXX&mode=0
On Hero 4 Black (last firmware) it gives error 404.

I figured out that **https** should be used instead of **http**.
https://10.5.5.9/gpPair?c=start&pin=XXXXXX&mode=0

####Details:

* GoPro Camera(s): Hero 4 Black
* Firmware Version: 4.0.0
* Steps to reproduce: connect via WiFi, try to pair
* Happens every time? [Y/N]: Y

**Comment by KonradIT** [comment]
Fixed in commit e6f12b9, thanks!
