### ISSUE TITLE
set metadata

### ISSUE THREAD

**Issue by cannibal-flea** [KonradIT/goprowifihack#52]
I am wondering if there is a way to pass metadata to the GoPro so it can be stored with the images. I see that the app is able to send and embed gps into the metadata. Is there a way to do this through the wifi api (for gps and any other arbitrary meta data)?

**Comment by KonradIT** [comment]
@cannibal-flea can you provide an example? All the photos I download w/ the GoPro App don't have any GPS EXIF in them
