### ISSUE TITLE
Add Firmware Archive Folder

### ISSUE THREAD

**Issue by silent3rror** [KonradIT/goprowifihack#55]
####Problem:
Downgrades need to be made available
####Details:
Need to create a folder with all of the GoPro HERO 4 (Black | Silver | Session) and HERO 5 (Black | Session) firmware
* GoPro Camera(s):
HERO4 BL|SL|SE and HERO5 BL|SE
* Firmware Version:
All possible versions that you can get your hands on
* Steps to reproduce:
N/A
* Happens every time? [Y/N]:
N/A

**Comment by KonradIT** [comment]
Hey,

I made this repo now for Firmware backup: https://github.com/KonradIT/gpfw-backup

Push all your future files there, I'll do the same!
