### ISSUE TITLE
SD Card Inserted property has values different to the documentation

### ISSUE THREAD

**Issue by RobLeighton** [KonradIT/goprowifihack#56]
####SD Card Inserted Status object property (33) has values different to the documentation:

####Startup with an SD Card Inserted - value = 0, remove card and value becomes 2:

* GoPro Camera(s): Hero4 Black
* Firmware Version: v03.00
* Steps to reproduce: Request Status/Settings object via wifi
* Happens every time? [Y/N]: Yes

**Comment by KonradIT** [comment]
I'll fix that now

**Comment by KonradIT** [comment]
Fixed in #412f65d

**Comment by RobLeighton** [comment]
I'm not sure the change reflects what I said - get 0 with an SD Card in and 2 if I remove it ?
