### ISSUE TITLE
how to obtain the camera serial number, that is tcp protocol

### ISSUE THREAD

**Issue by Qiyun2014** [KonradIT/goprowifihack#59]
####Problem:

####Details:

* GoPro Camera(s):
* Firmware Version:
* Steps to reproduce:
* Happens every time? [Y/N]:

**Comment by KonradIT** [comment]
You can obtain the camera's serial number (for HERO+, HERO4 and HERO5) here: https://github.com/KonradIT/goprowifihack/blob/master/HERO4/gpControl-Hero4Black.json#L5136

**Comment by Qiyun2014** [comment]
thank you, konradIT
