### ISSUE TITLE
Hero Session - ffplay error -bind failed: Address already in use

### ISSUE THREAD

**Issue by fawadniazi** [KonradIT/goprowifihack#63]
####Problem:

Manage to stream video using GoProStream.py
However when I try this command ` ffplay -fflags nobuffer -f:v mpegts -probesize 8192 udp://:8554`  it shows this error 

`ffplay -fflags nobuffer -f:v mpegts -probesize 8192 udp://:8554

ffplay version 3.2.2 Copyright (c) 2003-2016 the FFmpeg developers
  built with Apple LLVM version 8.0.0 (clang-800.0.42.1)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/3.2.2 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-libmp3lame --enable-libx264 --enable-libxvid --enable-opencl --disable-lzma --enable-vda
  libavutil      55. 34.100 / 55. 34.100
  libavcodec     57. 64.101 / 57. 64.101
  libavformat    57. 56.100 / 57. 56.100
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libavresample   3.  1.  0 /  3.  1.  0
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100
[udp @ 0x7f8a2f9ae760] bind failed: Address already in use
udp://:8554: Input/output error`

####Details:

* GoPro Camera(s):
* Firmware Version:
* Steps to reproduce:
* Happens every time? [Y/N]:

**Comment by KonradIT** [comment]
Restart your computer, use [this script instead[(http://github.com/konradit/goprostream)
