### ISSUE TITLE
HERO 4

### ISSUE THREAD

**Issue by incipio-venkat** [KonradIT/goprowifihack#7]
Any ideas on how to stream on ios app(HERO 4).I have Tried several ways but failed to stream?
Thank you..

**Comment by scottnath** [comment]
@incipio-venkat did you find a solution for the hero4? From what I've seen it looks like gopro might have turned live-streaming off for the gopro...wondering if there is a way to turn it back on...

**Comment by KonradIT** [comment]
Its now done over UDP, here is the url: udp://:8554
