### ISSUE TITLE
HERO5 Firmware Update 2.00

### ISSUE THREAD

**Issue by KonradIT** [KonradIT/goprowifihack#70]
The new update introduces [new protune controls for photo and multishot](https://twitter.com/David_Newman/status/849723785892712448)

Here is the changelog:

**Highlights:**

  * **Added new languages for camera and voice control**
  * **Applied existing settings to more capture modes**
  * **Added GoPro Plus features**

**Usability Improvements**

  * Adds Korean, Russian, and Portuguese (Brazil) as options for camera and voice control languages*
  * Adds setting for date and time format, based on language selection 
  * Includes touch display optimizations
  * Adds ability to extract a photo from a multi-shot series

**Performance Improvements**

  * Adds Shutter setting for Photo capture mode in Protune™ (options are AUTO, 1/125, 1/250, 1/500, 1/1000, 1/2000 second)
  * Adds Wide Dynamic Range (WDR) for Time Lapse Photo (intervals of at least 5 seconds)
  * Adds RAW Format for Time Lapse Photo and Night Lapse Photo (intervals of at least 5 seconds)
  * Adds RAW Format for Night photo

**GoPro Plus Improvements**

  * Allows manual upload of selected content

--- 

The command for 4K 24FPS for HERO5 Session should be the same as HERO5 Black. 

Needed: 

* shutter setting for Photo capture
* WDR for TimeLapse
* RAW format for TimeLapse/NightLapse
* RAW format for NightPhoto 
* Adds ability to extract a photo from a multi-shot series (?)

**Comment by B3nD3lan3y** [comment]
Has anyone experienced wake-over-LAN issues after this update? I'm working with some Hero 5 Sessions, updated one, and am now having issues waking it up.

**Comment by KonradIT** [comment]
@B3nD3lan3y any error logs?

**Comment by KonradIT** [comment]
5a4161f973d9c467fcad98656143d93ed69e59e9
