### ISSUE TITLE
stream

### ISSUE THREAD

**Issue by ningxiaoixao** [KonradIT/goprowifihack#8]
hi.
this URL doesn't work
`http://10.5.5.9/gp/gpExec?p1=gpStreamA9&c1=restart`
return this
`{
"version": "3.00",
"path_info": "/execute",
"query_string": "p1=gpStream&c1=restart",
"error_code": -3,
"error_msg": "unknown request",
"function": "control_router",
"line": 461 
}`

but this does work
`http://10.5.5.9/gp/gpExec?p1=gpStreamA9&c1=restart`

..udp://:8554 doesn't work.......

do u know new URL?

think u

**Comment by KonradIT** [comment]
udp://:8554 should work with both URLs. (http://10.5.5.9/gp/gpControl/execute?p1=gpStream&c1=restart and http://10.5.5.9/gp/gpExec?p1=gpStreamA9&c1=restart)

And try this one: http://10.5.5.9/gp/gpExec?p1=gpStreamA9&c1=restart
