### ISSUE TITLE
Android MediaPlayer to display frames (Android FFmpeg library)

### ISSUE THREAD

**Issue by chri1389** [KonradIT/goprowifihack#85]
**Problem:**
I have developed an Android App that use the Android FFmpeg library, from this link:
http://writingminds.github.io/ffmpeg-android-java/

Thank to this Library, I can take the frames (from a live streaming of a GoPro Hero4), but the library calls 
always the `onProgress(String message)` method, and "String message" parameter has that values:

`frame=  262 fps= 67 q=29.0 size=      46kB time=00:00:09.00 bitrate=  41.8kbits/s dup=199 drop=0 speed=2.31x`
`frame=  276 fps= 62 q=29.0 size=      60kB time=00:00:09.47 bitrate=  51.9kbits/s dup=200 drop=0 speed=2.12x`
`frame=  296 fps= 59 q=26.0 size=      72kB time=00:00:10.11 bitrate=  58.0kbits/s dup=200 drop=0 speed=   2x`
etc....

Can I use an Android MediaPlayer (for example VideoView) to display this frames? How can I do this?

Thank you very much!! 

Best regards!

**Comment by KonradIT** [comment]
Already answered in one of your million issue threads.
