### ISSUE TITLE
How do I use the commands in HERO5-Commands.md?

### ISSUE THREAD

**Issue by garydelarosausername** [KonradIT/goprowifihack#88]
**Problem:**

Title says it.

**Details:**

* GoPro Camera(s): Hero5 Black
* Firmware Version: 02.51
* Steps to reproduce: 
* Happens every time? [Y/N]:

**Comment by KonradIT** [comment]
Use the URLs with a HTTP library of your choice (eg: curl, aria2, urllib, requests...)
