### ISSUE TITLE
Android - Take frame from SurfaceView/VideoView

### ISSUE THREAD

**Issue by chri1389** [KonradIT/goprowifihack#91]
**How to take a bitmap from a SurfaceView/VideoView Android?**

Hello!
I can use in Android, a SurfaceView or a VideoView (indifferently) to display a live stream from an udp URL.
My question is: Can I take a bitmap from the SurfaceView/VideoView at a given instant? How?

I have tried to do the screenshot of the screen, with this code:
`View v1 = getWindow().getDecorView().getRootView();`
`v1.setDrawingCacheEnabled(true);`
`Bitmap bitmap = Bitmap.createBitmap(v1.getDrawingCache());`
but it take the screenshot without the status bar and the videoview is black.. If I use the classic key combination, the screenshot display the videoview correctly and the status bar etc... 
How can I resolve this problem? How can do a completely screenshot (in Java) that take the videoview frame, status bar etc...?

Thank you very much!

Best Regards!

**Comment by KonradIT** [comment]
My guess would be to use GLES glReadPixels()
